// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-29
//
// Rates are per 1M tokens, in the currency the provider bills in,
// and are given per billable class: a voice session's classes are
// priced far enough apart that one figure would say nothing.
//
// A DEFAULT, not an authority. A vendor's rate card changes without
// notice, so a caller that lets an operator state a rate must let
// that rate win over this one.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/realtime"
)

// Model IDs served by this catalog.
const (
	GPT4OMiniRealtime string = "gpt-4o-mini-realtime"
	GPT4ORealtime     string = "gpt-4o-realtime"
	GPTRealtime       string = "gpt-realtime"
	GPTRealtime15     string = "gpt-realtime-1.5"
	GPTRealtime2      string = "gpt-realtime-2"
	GPTRealtime21     string = "gpt-realtime-2.1"
	GPTRealtime21Mini string = "gpt-realtime-2.1-mini"
	GPTRealtimeMini   string = "gpt-realtime-mini"
)

// Models maps model IDs to their configurations.
var Models = map[string]realtime.Model{
	GPT4OMiniRealtime: {
		ID:       GPT4OMiniRealtime,
		Name:     "",
		Provider: "openai",
		APIModel: "gpt-4o-mini-realtime",
		Currency: "USD",
	},
	GPT4ORealtime: {
		ID:       GPT4ORealtime,
		Name:     "",
		Provider: "openai",
		APIModel: "gpt-4o-realtime",
		Currency: "USD",
	},
	GPTRealtime: {
		ID:                     GPTRealtime,
		Name:                   "GPT-Realtime",
		Provider:               "openai",
		APIModel:               "gpt-realtime",
		Currency:               "USD",
		CostPer1MTextIn:        4,
		CostPer1MTextInCached:  0.4,
		CostPer1MTextOut:       16,
		CostPer1MAudioIn:       32,
		CostPer1MAudioInCached: 0.4,
		CostPer1MAudioOut:      64,
		CostPer1MImageIn:       5,
		CostPer1MImageInCached: 0.5,
	},
	GPTRealtime15: {
		ID:                     GPTRealtime15,
		Name:                   "GPT-Realtime-1.5",
		Provider:               "openai",
		APIModel:               "gpt-realtime-1.5",
		Currency:               "USD",
		CostPer1MTextIn:        4,
		CostPer1MTextInCached:  0.4,
		CostPer1MTextOut:       16,
		CostPer1MAudioIn:       32,
		CostPer1MAudioInCached: 0.4,
		CostPer1MAudioOut:      64,
		CostPer1MImageIn:       5,
		CostPer1MImageInCached: 0.5,
	},
	GPTRealtime2: {
		ID:                     GPTRealtime2,
		Name:                   "GPT-Realtime-2",
		Provider:               "openai",
		APIModel:               "gpt-realtime-2",
		Currency:               "USD",
		CostPer1MTextIn:        4,
		CostPer1MTextInCached:  0.4,
		CostPer1MTextOut:       24,
		CostPer1MAudioIn:       32,
		CostPer1MAudioInCached: 0.4,
		CostPer1MAudioOut:      64,
		CostPer1MImageIn:       5,
		CostPer1MImageInCached: 0.5,
	},
	GPTRealtime21: {
		ID:                     GPTRealtime21,
		Name:                   "GPT-Realtime-2.1",
		Provider:               "openai",
		APIModel:               "gpt-realtime-2.1",
		Currency:               "USD",
		CostPer1MTextIn:        4,
		CostPer1MTextInCached:  0.4,
		CostPer1MTextOut:       24,
		CostPer1MAudioIn:       32,
		CostPer1MAudioInCached: 0.4,
		CostPer1MAudioOut:      64,
		CostPer1MImageIn:       5,
		CostPer1MImageInCached: 0.5,
	},
	GPTRealtime21Mini: {
		ID:                     GPTRealtime21Mini,
		Name:                   "GPT-Realtime-2.1 mini",
		Provider:               "openai",
		APIModel:               "gpt-realtime-2.1-mini",
		Currency:               "USD",
		CostPer1MTextIn:        0.6,
		CostPer1MTextInCached:  0.06,
		CostPer1MTextOut:       2.4,
		CostPer1MAudioIn:       10,
		CostPer1MAudioInCached: 0.3,
		CostPer1MAudioOut:      20,
		CostPer1MImageIn:       0.8,
		CostPer1MImageInCached: 0.08,
	},
	GPTRealtimeMini: {
		ID:                     GPTRealtimeMini,
		Name:                   "GPT-Realtime mini",
		Provider:               "openai",
		APIModel:               "gpt-realtime-mini",
		Currency:               "USD",
		CostPer1MTextIn:        0.6,
		CostPer1MTextInCached:  0.06,
		CostPer1MTextOut:       2.4,
		CostPer1MAudioIn:       10,
		CostPer1MAudioInCached: 0.3,
		CostPer1MAudioOut:      20,
		CostPer1MImageIn:       0.8,
		CostPer1MImageInCached: 0.08,
	},
}
