// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-08-29
//
// Rates are per 1000 invocations, in the currency the provider
// bills in -- the unit the provider publishes, kept rather than
// scaled, so no factor of a thousand hides in a generated file.
//
// A tool's tokens are NOT here. A provider that bills a search per
// call also bills the text that search read, at the calling model's
// own rates, so a total carrying only this rate is short by the
// larger half.
//
// A DEFAULT, not an authority. A vendor's rate card changes without
// notice, so a caller that lets an operator state a rate must let
// that rate win over this one.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/tools"
)

// Model IDs served by this catalog.
const (
	AgentKit   string = "agent-kit"
	Containers string = "containers"
	FileSearch string = "file-search"
	WebSearch  string = "web-search"
)

// Models maps model IDs to their configurations.
var Models = map[string]tools.Tool{
	AgentKit: {
		ID:       AgentKit,
		Name:     "Agent Kit",
		Provider: "openai",
		APIModel: "agent-kit",
		Currency: "USD",
	},
	Containers: {
		ID:       Containers,
		Name:     "Containers",
		Provider: "openai",
		APIModel: "containers",
		Currency: "USD",
	},
	FileSearch: {
		ID:             FileSearch,
		Name:           "File search",
		Provider:       "openai",
		APIModel:       "file-search",
		Currency:       "USD",
		CostPer1KCalls: 2.5,
	},
	WebSearch: {
		ID:             WebSearch,
		Name:           "Web search",
		Provider:       "openai",
		APIModel:       "web-search",
		Currency:       "USD",
		CostPer1KCalls: 10,
	},
}
